# Generated by Django 6.0 on 2025-12-18 09:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_guest_identities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_text', models.TextField()),
                ('category_user_selected', models.CharField(choices=[('family', 'Family'), ('faith', 'Faith'), ('health', 'Health'), ('spouse', 'Spouse'), ('children', 'Children'), ('parenting', 'Parenting'), ('finances', 'Finances'), ('guidance', 'Guidance'), ('other', 'Other')], default='other', max_length=32)),
                ('category_ml_suggested', models.CharField(blank=True, choices=[('family', 'Family'), ('faith', 'Faith'), ('health', 'Health'), ('spouse', 'Spouse'), ('children', 'Children'), ('parenting', 'Parenting'), ('finances', 'Finances'), ('guidance', 'Guidance'), ('other', 'Other')], max_length=32, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('praying', 'Praying'), ('prayed', 'Prayed'), ('closed', 'Closed')], default='new', max_length=16)),
                ('guest_identity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to='prayers.guestidentity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, default='')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_assignments', to=settings.AUTH_USER_MODEL)),
                ('prayer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='prayers.prayerrequest')),
            ],
        ),
    ]
